<script lang="ts">
  import { get } from 'svelte/store';
  import { graphStore, selectedNode } from '../../stores/graph';
  import { t } from '../../stores/i18n';
  import {
    defineComponent,
    defineComponentAction,
    defineComponentState,
  } from '../../workstation/registry';

  // Register with the workstation self-introspection registry. See #64.
  defineComponent({
    id: 'context-editor',
    role: 'CONTEXT.md editor for the currently-selected node — shows the raw markdown with edit mode and injection-risk badge',
    parent: 'workstation-layout',
    actions: {
      'start-edit':   {},
      'cancel-edit':  {},
      'save':         { args: { content: 'string?' } },
      'set-content':  { args: { content: 'string' } },
    },
    state: [
      'selected-node-id',
      'selected-node-path',
      'is-edit-mode',
      'is-manually-edited',
      'content-line-count',
      'injection-risk-severity',
      'injection-risk-reason',
    ],
  });

  defineComponentAction('context-editor', 'start-edit', () => {
    const n = get(selectedNode);
    if (!n) throw new Error('no node selected');
    startEdit();
    return { ok: true };
  });
  defineComponentAction('context-editor', 'cancel-edit', () => {
    cancelEdit();
    return { ok: true };
  });
  defineComponentAction('context-editor', 'save', ({ content }) => {
    if (typeof content === 'string') editContent = content;
    saveEdit();
    return { ok: true };
  });
  defineComponentAction('context-editor', 'set-content', ({ content }) => {
    if (typeof content !== 'string') throw new Error('content must be a string');
    editContent = content;
    return { ok: true };
  });

  defineComponentState('context-editor', 'selected-node-id', () => get(selectedNode)?.id ?? null);
  defineComponentState('context-editor', 'selected-node-path', () => get(selectedNode)?.path ?? null);
  defineComponentState('context-editor', 'is-edit-mode', () => editMode);
  defineComponentState('context-editor', 'is-manually-edited', () =>
    get(selectedNode)?.contextFile?.manuallyEdited === true,
  );
  defineComponentState('context-editor', 'content-line-count', () =>
    get(selectedNode)?.contextFile?.lineCount ?? 0,
  );
  defineComponentState('context-editor', 'injection-risk-severity', () => injectionRisk.severity);
  defineComponentState('context-editor', 'injection-risk-reason', () => injectionRisk.reason);

  $: node = $selectedNode;
  $: contextContent = node?.contextFile?.rawMarkdown || '';
  $: isManual = node?.contextFile?.manuallyEdited || false;

  // Client-side scan for obvious injection patterns in the displayed content.
  // This is a safety net for manually-edited files that bypass the sanitizer.
  $: injectionRisk = scanForInjection(contextContent);

  function scanForInjection(text: string): { severity: 'high' | 'medium' | 'low' | null; reason: string } {
    if (!text) return { severity: null, reason: '' };
    const patterns: Array<{ re: RegExp; severity: 'high' | 'medium' | 'low'; reason: string }> = [
      { re: /\b(?:ignore|disregard|forget|override)\s+(?:all\s+)?(?:previous|prior|above|earlier)\s+instructions?\b/i, severity: 'high', reason: 'Direct instruction override' },
      { re: /<\s*system\b|<\|im_start\|>|<\|system\|>/i, severity: 'high', reason: 'System prompt spoofing tag' },
      { re: /^\s*(?:system|assistant)\s*:/im, severity: 'high', reason: 'Role-prefix line' },
      { re: /\byou\s+are\s+now\s+|pretend\s+(?:to\s+be|you\s+are)|act\s+as\s+(?:if|a|an)\b/i, severity: 'medium', reason: 'Role-override phrase' },
      { re: /\b(?:DAN|jailbreak|unrestricted)\s+mode\b/i, severity: 'medium', reason: 'Jailbreak phrase' },
      { re: /\b(?:leak|exfiltrate)\s+(?:env|secret|token|credential)/i, severity: 'medium', reason: 'Data exfiltration request' },
      { re: /[\u202A-\u202E\u2066-\u2069]/, severity: 'low', reason: 'Bidirectional override character' },
    ];
    for (const p of patterns) {
      if (p.re.test(text)) {
        return { severity: p.severity, reason: p.reason };
      }
    }
    return { severity: null, reason: '' };
  }

  let editMode = false;
  let editContent = '';

  function startEdit() {
    editContent = contextContent;
    editMode = true;
  }

  function cancelEdit() {
    editMode = false;
    editContent = '';
  }

  function saveEdit() {
    if (!node || !$graphStore) return;
    const updatedNode = $graphStore.nodes.get(node.id);
    if (updatedNode && updatedNode.contextFile) {
      updatedNode.contextFile.rawMarkdown = editContent;
      updatedNode.contextFile.manuallyEdited = true;
      updatedNode.contextFile.lineCount = editContent.split('\n').length;
    }
    editMode = false;
    graphStore.set($graphStore);
  }
</script>

<div class="context-editor">
  {#if node}
    <div class="editor-header">
      <h4>{node.name}/CONTEXT.md</h4>
      <span class="edit-badge" class:manual={isManual}>
        {isManual ? $t('editor.manualEdit') : $t('editor.autoGenerated')}
      </span>
      {#if injectionRisk.severity}
        <span class="security-badge" class:high={injectionRisk.severity === 'high'} class:medium={injectionRisk.severity === 'medium'} class:low={injectionRisk.severity === 'low'} title="{injectionRisk.severity === 'high' ? 'Untrusted — review before using' : 'Suspicious content detected'}: {injectionRisk.reason}">
          {#if injectionRisk.severity === 'high'}⚠ untrusted{:else if injectionRisk.severity === 'medium'}! suspicious{:else}low risk{/if}
        </span>
      {/if}
      <span class="editor-meta">L{node.layer} · {node.path} · {node.children.length} barn{node.language ? ` · ${node.language}` : ''}</span>
      <div class="editor-actions">
        {#if editMode}
          <button class="btn btn-save" on:click={saveEdit}>{$t('editor.save')}</button>
          <button class="btn btn-cancel" on:click={cancelEdit}>{$t('editor.cancel')}</button>
        {:else}
          <button class="btn btn-edit" on:click={startEdit}>{$t('editor.title')}</button>
        {/if}
      </div>
    </div>

    <div class="editor-content">
      {#if editMode}
        <textarea
          class="edit-textarea"
          bind:value={editContent}
          spellcheck="false"
        ></textarea>
      {:else if contextContent}
        <pre class="context-preview">{contextContent}</pre>
      {:else}
        <div class="no-context">
          <p class="summary">{node.summary}</p>
          <p class="hint">Ingen CONTEXT.md generert for denne noden.</p>
        </div>
      {/if}
    </div>
  {:else}
    <div class="no-selection">
      <p>⟐ Velg en node for a se detaljer</p>
    </div>
  {/if}
</div>

<style>
  .context-editor { display: flex; flex-direction: column; height: 100%; background: #0f0f14; border-top: 1px solid #1f1f2e; }
  .editor-header { display: flex; align-items: center; padding: 6px 12px; border-bottom: 1px solid #1f1f2e; gap: 10px; flex-shrink: 0; }
  .editor-header h4 { margin: 0; font-size: 13px; color: #e5e7eb; white-space: nowrap; }
  .edit-badge { font-size: 10px; padding: 1px 6px; border-radius: 3px; background: rgba(16, 185, 129, 0.15); color: #10b981; flex-shrink: 0; }
  .edit-badge.manual { background: rgba(245, 158, 11, 0.15); color: #f59e0b; }
  .security-badge {
    font-size: 10px; padding: 1px 6px; border-radius: 3px;
    flex-shrink: 0; font-weight: 700;
    cursor: help;
  }
  .security-badge.high {
    background: rgba(239, 68, 68, 0.18); color: #f87171;
    border: 1px solid rgba(239, 68, 68, 0.35);
  }
  .security-badge.medium {
    background: rgba(245, 158, 11, 0.15); color: #fbbf24;
    border: 1px solid rgba(245, 158, 11, 0.3);
  }
  .security-badge.low {
    background: rgba(107, 114, 128, 0.15); color: #9ca3af;
    border: 1px solid rgba(107, 114, 128, 0.25);
  }
  .editor-meta { font-size: 11px; color: #6b7280; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .editor-actions { display: flex; gap: 6px; }
  .btn { padding: 4px 12px; border: 1px solid #2d2d3d; border-radius: 4px; font-size: 11px; cursor: pointer; background: #1a1a24; color: #9ca3af; }
  .btn-save { background: rgba(16, 185, 129, 0.15); border-color: #10b981; color: #10b981; }
  .btn-cancel { color: #6b7280; }
  .btn-edit { color: #3b82f6; border-color: #3b82f6; }
  .editor-content { flex: 1; overflow: auto; padding: 12px; }
  .context-preview { margin: 0; font-size: 12px; color: #d1d5db; white-space: pre-wrap; font-family: 'JetBrains Mono', 'Fira Code', monospace; line-height: 1.5; }
  .edit-textarea { width: 100%; height: 100%; min-height: 200px; background: #1a1a24; border: 1px solid #2d2d3d; border-radius: 6px; color: #e5e7eb; font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 12px; line-height: 1.5; padding: 12px; resize: none; outline: none; }
  .edit-textarea:focus { border-color: #3b82f6; }
  .no-context { padding: 20px; text-align: center; }
  .no-context .summary { color: #9ca3af; font-size: 13px; margin-bottom: 8px; }
  .no-context .hint { color: #4b5563; font-size: 12px; }
  .no-selection { display: flex; align-items: center; justify-content: center; height: 100%; color: #4b5563; font-size: 14px; }
</style>
