<script lang="ts">
  import { graphStore, selectedNode } from '../../stores/graph';
  import { t } from '../../stores/i18n';

  $: node = $selectedNode;
  $: contextContent = node?.contextFile?.rawMarkdown || '';
  $: isManual = node?.contextFile?.manuallyEdited || false;

  let editMode = false;
  let editContent = '';

  function startEdit() {
    editContent = contextContent;
    editMode = true;
  }

  function cancelEdit() {
    editMode = false;
    editContent = '';
  }

  function saveEdit() {
    if (!node || !$graphStore) return;
    const updatedNode = $graphStore.nodes.get(node.id);
    if (updatedNode && updatedNode.contextFile) {
      updatedNode.contextFile.rawMarkdown = editContent;
      updatedNode.contextFile.manuallyEdited = true;
      updatedNode.contextFile.lineCount = editContent.split('\n').length;
    }
    editMode = false;
    graphStore.set($graphStore);
  }
</script>

<div class="context-editor">
  {#if node}
    <div class="editor-header">
      <h4>{node.name}/CONTEXT.md</h4>
      <span class="edit-badge" class:manual={isManual}>
        {isManual ? $t('editor.manualEdit') : $t('editor.autoGenerated')}
      </span>
      <span class="editor-meta">L{node.layer} · {node.path} · {node.children.length} barn{node.language ? ` · ${node.language}` : ''}</span>
      <div class="editor-actions">
        {#if editMode}
          <button class="btn btn-save" on:click={saveEdit}>{$t('editor.save')}</button>
          <button class="btn btn-cancel" on:click={cancelEdit}>{$t('editor.cancel')}</button>
        {:else}
          <button class="btn btn-edit" on:click={startEdit}>{$t('editor.title')}</button>
        {/if}
      </div>
    </div>

    <div class="editor-content">
      {#if editMode}
        <textarea
          class="edit-textarea"
          bind:value={editContent}
          spellcheck="false"
        ></textarea>
      {:else if contextContent}
        <pre class="context-preview">{contextContent}</pre>
      {:else}
        <div class="no-context">
          <p class="summary">{node.summary}</p>
          <p class="hint">Ingen CONTEXT.md generert for denne noden.</p>
        </div>
      {/if}
    </div>
  {:else}
    <div class="no-selection">
      <p>⟐ Velg en node for a se detaljer</p>
    </div>
  {/if}
</div>

<style>
  .context-editor { display: flex; flex-direction: column; height: 100%; background: #0f0f14; border-top: 1px solid #1f1f2e; }
  .editor-header { display: flex; align-items: center; padding: 6px 12px; border-bottom: 1px solid #1f1f2e; gap: 10px; flex-shrink: 0; }
  .editor-header h4 { margin: 0; font-size: 13px; color: #e5e7eb; white-space: nowrap; }
  .edit-badge { font-size: 10px; padding: 1px 6px; border-radius: 3px; background: rgba(16, 185, 129, 0.15); color: #10b981; flex-shrink: 0; }
  .edit-badge.manual { background: rgba(245, 158, 11, 0.15); color: #f59e0b; }
  .editor-meta { font-size: 11px; color: #6b7280; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .editor-actions { display: flex; gap: 6px; }
  .btn { padding: 4px 12px; border: 1px solid #2d2d3d; border-radius: 4px; font-size: 11px; cursor: pointer; background: #1a1a24; color: #9ca3af; }
  .btn-save { background: rgba(16, 185, 129, 0.15); border-color: #10b981; color: #10b981; }
  .btn-cancel { color: #6b7280; }
  .btn-edit { color: #3b82f6; border-color: #3b82f6; }
  .editor-content { flex: 1; overflow: auto; padding: 12px; }
  .context-preview { margin: 0; font-size: 12px; color: #d1d5db; white-space: pre-wrap; font-family: 'JetBrains Mono', 'Fira Code', monospace; line-height: 1.5; }
  .edit-textarea { width: 100%; height: 100%; min-height: 200px; background: #1a1a24; border: 1px solid #2d2d3d; border-radius: 6px; color: #e5e7eb; font-family: 'JetBrains Mono', 'Fira Code', monospace; font-size: 12px; line-height: 1.5; padding: 12px; resize: none; outline: none; }
  .edit-textarea:focus { border-color: #3b82f6; }
  .no-context { padding: 20px; text-align: center; }
  .no-context .summary { color: #9ca3af; font-size: 13px; margin-bottom: 8px; }
  .no-context .hint { color: #4b5563; font-size: 12px; }
  .no-selection { display: flex; align-items: center; justify-content: center; height: 100%; color: #4b5563; font-size: 14px; }
</style>
