/**
 * Internationalization store.
 * Norwegian Bokmal (nb) is the default. English (en) as fallback.
 */

import { writable, derived } from 'svelte/store';

export type Locale = 'nb' | 'en';

export const locale = writable<Locale>('nb');

const translations: Record<Locale, Record<string, string>> = {
  nb: {
    // Navigation
    'nav.tree': 'Mappevisning',
    'nav.graph': 'Grafvisning',
    'nav.split': 'Delt visning',
    'nav.settings': 'Innstillinger',
    'nav.analytics': 'Analyse',

    // Main
    'app.title': 'Klonode',
    'app.subtitle': 'AI-kontekstrutering',
    'app.noProject': 'Ingen prosjekt lastet',
    'app.loadProject': 'Last inn prosjekt',

    // Tree view
    'tree.title': 'Mappestruktur',
    'tree.search': 'Sok i mapper...',
    'tree.empty': 'Ingen mapper funnet',
    'tree.files': 'filer',
    'tree.dirs': 'mapper',

    // Graph view
    'graph.title': 'Rutingsgraf',
    'graph.nodes': 'noder',
    'graph.edges': 'kanter',
    'graph.zoom': 'Zoom',
    'graph.fitView': 'Tilpass visning',
    'graph.toggleHeatmap': 'Vis varmekart',

    // Editor
    'editor.title': 'Rediger CONTEXT.md',
    'editor.save': 'Lagre',
    'editor.cancel': 'Avbryt',
    'editor.inputs': 'Inndata',
    'editor.process': 'Prosess',
    'editor.outputs': 'Utdata',
    'editor.manualEdit': 'Manuelt redigert',
    'editor.autoGenerated': 'Auto-generert',

    // Status
    'status.coverage': 'Dekning',
    'status.tokens': 'Tokens',
    'status.sessions': 'Sesjoner',
    'status.optimize': 'Optimaliser',
    'status.healthy': 'Frisk',
    'status.needsWork': 'Trenger arbeid',

    // Layers
    'layer.0': 'Lag 0 — Rotnavigasjon',
    'layer.1': 'Lag 1 — Oppgaveruting',
    'layer.2': 'Lag 2 — Stegkontrakt',
    'layer.3': 'Lag 3 — Referansemateriale',
    'layer.4': 'Lag 4 — Arbeidsartefakter',

    // Actions
    'action.init': 'Generer ruting',
    'action.optimize': 'Optimaliser ruting',
    'action.export': 'Eksporter',
    'action.import': 'Importer',
    'action.regenerate': 'Regenerer',
  },
  en: {
    'nav.tree': 'Tree View',
    'nav.graph': 'Graph View',
    'nav.split': 'Split View',
    'nav.settings': 'Settings',
    'nav.analytics': 'Analytics',

    'app.title': 'Klonode',
    'app.subtitle': 'AI Context Routing',
    'app.noProject': 'No project loaded',
    'app.loadProject': 'Load Project',

    'tree.title': 'Folder Structure',
    'tree.search': 'Search folders...',
    'tree.empty': 'No folders found',
    'tree.files': 'files',
    'tree.dirs': 'directories',

    'graph.title': 'Routing Graph',
    'graph.nodes': 'nodes',
    'graph.edges': 'edges',
    'graph.zoom': 'Zoom',
    'graph.fitView': 'Fit View',
    'graph.toggleHeatmap': 'Toggle Heatmap',

    'editor.title': 'Edit CONTEXT.md',
    'editor.save': 'Save',
    'editor.cancel': 'Cancel',
    'editor.inputs': 'Inputs',
    'editor.process': 'Process',
    'editor.outputs': 'Outputs',
    'editor.manualEdit': 'Manually edited',
    'editor.autoGenerated': 'Auto-generated',

    'status.coverage': 'Coverage',
    'status.tokens': 'Tokens',
    'status.sessions': 'Sessions',
    'status.optimize': 'Optimize',
    'status.healthy': 'Healthy',
    'status.needsWork': 'Needs work',

    'layer.0': 'Layer 0 — Root Navigation',
    'layer.1': 'Layer 1 — Task Routing',
    'layer.2': 'Layer 2 — Stage Contract',
    'layer.3': 'Layer 3 — Reference Material',
    'layer.4': 'Layer 4 — Working Artifacts',

    'action.init': 'Generate Routing',
    'action.optimize': 'Optimize Routing',
    'action.export': 'Export',
    'action.import': 'Import',
    'action.regenerate': 'Regenerate',
  },
};

/**
 * Translation function. Usage: $t('nav.tree')
 */
export const t = derived(locale, ($locale) => {
  return (key: string): string => {
    return translations[$locale]?.[key] || translations.en[key] || key;
  };
});
